# Generated by Django 2.2 on 2020-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlike',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
